theme: jekyll-theme-architect
show_downloads: false
title: Micro Frontends
description: Microservice fikrinin frontend geliştirmeye uyarlanması
github:
  is_project_page: true
  repository_url: https://github.com/neuland/micro-frontends
exclude:
  - 2-composition-universal
  - 3-data-fetching
  - node_modules
